# Start from Maven official image
FROM maven:3.9.6-eclipse-temurin-17

# Install Docker CLI (latest)
RUN apt-get update && \
    apt-get install -y docker.io && \
    rm -rf /var/lib/apt/lists/*

# Set working directory
WORKDIR /app

# By default, open shell for interactive use
CMD ["bash"]